# Generated by Django 4.2.7 on 2024-03-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='object3D',
            field=models.CharField(default='Teste', max_length=200),
            preserve_default=False,
        ),
    ]
